export const orders = [
  {
    id: "1",
    title: "Разработка Telegram бота на Python",
    description: "Нужен бот для автоматизации ответов и интеграции с CRM. Требования: aiogram, PostgreSQL.",
    platform: "FL.ru",
    budget: 500,
    currency: "USD",
    clientName: "Компания X",
    skills: ["Python", "Telegram API", "PostgreSQL"],
    status: "FILTERED",
    filterScore: 0.92,
    createdAt: "2025-03-12T10:00:00Z",
  },
  {
    id: "2",
    title: "Frontend React + TypeScript",
    description: "Landing page для SaaS продукта. Современный дизайн, адаптивность.",
    platform: "Upwork",
    budget: 800,
    currency: "USD",
    clientName: "John Doe",
    skills: ["React", "TypeScript", "Tailwind"],
    status: "NEW",
    filterScore: 0.88,
    createdAt: "2025-03-12T09:30:00Z",
  },
  {
    id: "3",
    title: "Backend API на Node.js",
    description: "REST API для мобильного приложения. JWT auth, MongoDB.",
    platform: "Freelancer",
    budget: 1200,
    currency: "USD",
    clientName: "Startup Inc",
    skills: ["Node.js", "MongoDB", "Express"],
    status: "APPROVED",
    filterScore: 0.95,
    createdAt: "2025-03-11T14:00:00Z",
  },
];
